import ast
import cmath
import math
import operator
import statistics
from collections import Counter
from io import BytesIO
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple

from PIL import Image, ImageDraw, ImageFont
from telegram import InputFile, Update
from telegram.ext import Application, CommandHandler, ContextTypes

from config import MAX_INPUT
from utils import split_long_text, text_to_file


# ============================================================
# General formatting helpers
# ============================================================

MAX_POLYNOMIAL_DEGREE = 20
MAX_PRIME_LIMIT = 1_000_000
MAX_PLOT_SAMPLES = 600
DEFAULT_PLOT_WIDTH = 1100
DEFAULT_PLOT_HEIGHT = 720


def clean_number(value: float, eps: float = 1e-10) -> float:
    if abs(value) < eps:
        return 0.0
    return value


def format_real_number(value: float, digits: int = 10) -> str:
    value = clean_number(float(value))
    if math.isfinite(value) and abs(value - round(value)) < 1e-10:
        return str(int(round(value)))
    return f"{value:.{digits}g}"


def format_complex_number(value: complex) -> str:
    real = clean_number(value.real)
    imag = clean_number(value.imag)

    if imag == 0:
        return format_real_number(real)
    if real == 0:
        return f"{format_real_number(imag)}i"

    sign = "+" if imag > 0 else "-"
    return f"{format_real_number(real)} {sign} {format_real_number(abs(imag))}i"


def now_note() -> str:
    return "Generated by AhBashin math module"


# ============================================================
# Safe expression evaluator
# ============================================================


def _cbrt(x: float) -> float:
    return math.copysign(abs(x) ** (1 / 3), x)


def _log(x: float, base: Optional[float] = None) -> float:
    if base is None:
        return math.log(x)
    return math.log(x, base)


def _ncr(n: float, r: float) -> int:
    return math.comb(int(n), int(r))


def _npr(n: float, r: float) -> int:
    return math.perm(int(n), int(r))


def _lcm(*values: float) -> int:
    ints = [int(v) for v in values]
    return math.lcm(*ints)


def _gcd(*values: float) -> int:
    ints = [int(v) for v in values]
    return math.gcd(*ints)


ALLOWED_FUNCTIONS: Dict[str, Callable[..., Any]] = {
    "abs": abs,
    "round": round,
    "min": min,
    "max": max,
    "sum": lambda *xs: sum(xs),
    "sqrt": math.sqrt,
    "cbrt": _cbrt,
    "pow": pow,
    "exp": math.exp,
    "log": _log,
    "ln": math.log,
    "log10": math.log10,
    "log2": math.log2,
    "sin": math.sin,
    "cos": math.cos,
    "tan": math.tan,
    "asin": math.asin,
    "acos": math.acos,
    "atan": math.atan,
    "atan2": math.atan2,
    "sinh": math.sinh,
    "cosh": math.cosh,
    "tanh": math.tanh,
    "degrees": math.degrees,
    "radians": math.radians,
    "floor": math.floor,
    "ceil": math.ceil,
    "factorial": lambda n: math.factorial(int(n)),
    "gamma": math.gamma,
    "gcd": _gcd,
    "lcm": _lcm,
    "ncr": _ncr,
    "comb": _ncr,
    "npr": _npr,
    "perm": _npr,
    "mean": lambda *xs: statistics.mean(xs),
    "median": lambda *xs: statistics.median(xs),
    "variance": lambda *xs: statistics.variance(xs),
    "stdev": lambda *xs: statistics.stdev(xs),
}

ALLOWED_CONSTANTS: Dict[str, float] = {
    "pi": math.pi,
    "π": math.pi,
    "e": math.e,
    "tau": math.tau,
    "τ": math.tau,
    "phi": (1 + math.sqrt(5)) / 2,
    "golden": (1 + math.sqrt(5)) / 2,
    "inf": math.inf,
    "infinity": math.inf,
    "nan": math.nan,
}

BIN_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.FloorDiv: operator.floordiv,
    ast.Mod: operator.mod,
    ast.Pow: operator.pow,
}

UNARY_OPS = {
    ast.UAdd: operator.pos,
    ast.USub: operator.neg,
}


class SafeEvalError(ValueError):
    pass


def normalize_expression(expr: str) -> str:
    return (
        expr.strip()
        .replace("^", "**")
        .replace("÷", "/")
        .replace("×", "*")
        .replace("−", "-")
        .replace("θ", "theta")
    )


def safe_eval_expression(expr: str, variables: Optional[Dict[str, float]] = None) -> float:
    expr = normalize_expression(expr)
    if not expr:
        raise SafeEvalError("Expression is empty.")
    if len(expr) > 500:
        raise SafeEvalError("Expression is too long.")

    names = dict(ALLOWED_CONSTANTS)
    if variables:
        names.update(variables)

    tree = ast.parse(expr, mode="eval")

    def eval_node(node: ast.AST) -> Any:
        if isinstance(node, ast.Expression):
            return eval_node(node.body)

        if isinstance(node, ast.Constant):
            if isinstance(node.value, (int, float)):
                return node.value
            raise SafeEvalError("Only numeric constants are allowed.")

        if isinstance(node, ast.Name):
            if node.id in names:
                return names[node.id]
            raise SafeEvalError(f"Unknown name: {node.id}")

        if isinstance(node, ast.BinOp):
            op_type = type(node.op)
            if op_type not in BIN_OPS:
                raise SafeEvalError("Operator is not allowed.")
            left = eval_node(node.left)
            right = eval_node(node.right)
            return BIN_OPS[op_type](left, right)

        if isinstance(node, ast.UnaryOp):
            op_type = type(node.op)
            if op_type not in UNARY_OPS:
                raise SafeEvalError("Unary operator is not allowed.")
            return UNARY_OPS[op_type](eval_node(node.operand))

        if isinstance(node, ast.Call):
            if not isinstance(node.func, ast.Name):
                raise SafeEvalError("Only simple function calls are allowed.")
            func_name = node.func.id
            if func_name not in ALLOWED_FUNCTIONS:
                raise SafeEvalError(f"Function not allowed: {func_name}")
            if len(node.args) > 10:
                raise SafeEvalError("Too many function arguments.")
            args = [eval_node(arg) for arg in node.args]
            return ALLOWED_FUNCTIONS[func_name](*args)

        raise SafeEvalError("Expression contains unsupported syntax.")

    result = eval_node(tree)
    if not isinstance(result, (int, float)):
        raise SafeEvalError("Expression did not return a number.")
    return float(result)


def evaluate_function(expr: str, variable_name: str, variable_value: float) -> float:
    variables = {
        variable_name: variable_value,
        "x": variable_value if variable_name == "x" else 0.0,
        "t": variable_value if variable_name == "t" else 0.0,
        "theta": variable_value if variable_name == "theta" else 0.0,
    }
    return safe_eval_expression(expr, variables)


# ============================================================
# Basic calculator commands
# ============================================================


async def calc_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return

    if not context.args:
        await update.message.reply_text(
            "Usage:\n/calc 2 + 2\n/calc sin(pi / 2)\n/calc ncr(10, 3)"
        )
        return

    expression = " ".join(context.args)
    try:
        result = safe_eval_expression(expression)
        await update.message.reply_text(
            f"Expression:\n{expression}\n\nResult:\n{format_real_number(result, digits=14)}"
        )
    except Exception as error:
        await update.message.reply_text(f"Calculator error.\n\nError: {error}")


async def pi_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message:
        await update.message.reply_text(f"π = {math.pi:.50f}")


async def e_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message:
        await update.message.reply_text(f"e = {math.e:.50f}")


# ============================================================
# Collatz and Fibonacci
# ============================================================


def parse_positive_int(args: Sequence[str], name: str = "number", max_value: int = MAX_INPUT) -> int:
    if not args:
        raise ValueError(f"Please provide a {name}.")
    text = "".join(args).replace(",", "").replace("_", "").strip()
    if not text.isdigit():
        raise ValueError(f"{name.capitalize()} must be a positive integer.")
    value = int(text)
    if value < 1:
        raise ValueError(f"{name.capitalize()} must be at least 1.")
    if value > max_value:
        raise ValueError(f"{name.capitalize()} is too large. Maximum allowed is {max_value}.")
    return value


def collatz_sequence(n: int) -> List[int]:
    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n //= 2
        else:
            n = 3 * n + 1
        sequence.append(n)
        if len(sequence) > 200_000:
            raise ValueError("Sequence became too long.")
    return sequence


async def collatz_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        n = parse_positive_int(context.args, "Collatz input")
        sequence = collatz_sequence(n)
        report = (
            f"Collatz sequence for {n}\n\n"
            f"Steps: {len(sequence) - 1}\n"
            f"Maximum value: {max(sequence)}\n\n"
            + " → ".join(str(x) for x in sequence)
        )
    except Exception as error:
        await update.message.reply_text(f"Collatz error.\n\nError: {error}\n\nUsage:\n/collatz 27")
        return

    if len(report) <= 3500:
        await update.message.reply_text(report)
    else:
        await update.message.reply_document(
            document=text_to_file(report, f"collatz_{n}.txt"),
            caption=f"Collatz sequence for {n}",
        )


def fibonacci_number(n: int) -> int:
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def fibonacci_list(n: int) -> List[int]:
    return [fibonacci_number(i) for i in range(n + 1)]


async def fib_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        n = parse_positive_int(context.args, "Fibonacci index", max_value=5000)
        value = fibonacci_number(n)
    except Exception as error:
        await update.message.reply_text(f"Fibonacci error.\n\nError: {error}\n\nUsage:\n/fib 100")
        return

    text = f"Fibonacci number\n\nF({n}) = {value}"
    if len(text) <= 3500:
        await update.message.reply_text(text)
    else:
        await update.message.reply_document(
            document=text_to_file(text, f"fibonacci_{n}.txt"),
            caption=f"F({n})",
        )


async def fiblist_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        n = parse_positive_int(context.args, "Fibonacci list limit", max_value=1000)
        values = fibonacci_list(n)
        text = f"Fibonacci list F(0) to F({n})\n\n" + ", ".join(str(x) for x in values)
    except Exception as error:
        await update.message.reply_text(f"Fibonacci list error.\n\nError: {error}\n\nUsage:\n/fiblist 30")
        return

    if len(text) <= 3500:
        await update.message.reply_text(text)
    else:
        await update.message.reply_document(
            document=text_to_file(text, f"fibonacci_list_{n}.txt"),
            caption=f"Fibonacci list to F({n})",
        )


# ============================================================
# Statistics
# ============================================================


def split_top_level_values(text: str) -> List[str]:
    parts = []
    current = []
    depth = 0

    for char in text:
        if char == "(":
            depth += 1
            current.append(char)
        elif char == ")":
            depth = max(0, depth - 1)
            current.append(char)
        elif char in ",;" and depth == 0:
            item = "".join(current).strip()
            if item:
                parts.append(item)
            current = []
        else:
            current.append(char)

    item = "".join(current).strip()
    if item:
        parts.append(item)

    return parts


def parse_number_list(args: Sequence[str]) -> List[float]:
    if not args:
        raise ValueError("Please provide numbers.")
    text = " ".join(args)
    raw_parts = split_top_level_values(text)
    if len(raw_parts) == 1 and "," not in text and ";" not in text:
        raw_parts = [part.strip() for part in text.split() if part.strip()]
    values = [safe_eval_expression(part) for part in raw_parts]
    if not values:
        raise ValueError("No numbers found.")
    return values


def mode_text(values: List[float]) -> str:
    rounded = [round(v, 12) for v in values]
    counts = Counter(rounded)
    highest = max(counts.values())
    if highest <= 1:
        return "Mo = ∅"
    if len(set(counts.values())) == 1:
        return "Mo = ∅"
    modes = [value for value, count in counts.items() if count == highest]
    return "Mo = " + ", ".join(format_real_number(v) for v in modes)


def build_stats_report(values: List[float]) -> str:
    sorted_values = sorted(values)
    count = len(values)
    total = sum(values)
    mean = statistics.mean(values)
    median = statistics.median(values)
    min_value = min(values)
    max_value = max(values)
    value_range = max_value - min_value

    lines = [
        "Statistics report",
        "",
        f"Count: n = {count}",
        f"Sum: Σx = {format_real_number(total)}",
        f"Mean: x̄ = {format_real_number(mean)}",
        f"Median: {format_real_number(median)}",
        f"Mode: {mode_text(values)}",
        f"Minimum: {format_real_number(min_value)}",
        f"Maximum: {format_real_number(max_value)}",
        f"Range: {format_real_number(value_range)}",
    ]

    if count >= 2:
        lines.extend(
            [
                f"Sample variance: s² = {format_real_number(statistics.variance(values))}",
                f"Sample standard deviation: s = {format_real_number(statistics.stdev(values))}",
                f"Population variance: σ² = {format_real_number(statistics.pvariance(values))}",
                f"Population standard deviation: σ = {format_real_number(statistics.pstdev(values))}",
            ]
        )

    lines.extend(["", "Sorted values:", ", ".join(format_real_number(v) for v in sorted_values)])
    return "\n".join(lines)


async def stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        values = parse_number_list(context.args)
        report = build_stats_report(values)
    except Exception as error:
        await update.message.reply_text(
            f"Statistics error.\n\nError: {error}\n\nUsage:\n/stats 4, pi, 4, sin(pi/2), 7, 2"
        )
        return

    for chunk in split_long_text(report):
        await update.message.reply_text(chunk)


async def statsfile_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        values = parse_number_list(context.args)
        report = build_stats_report(values)
    except Exception as error:
        await update.message.reply_text(f"Statistics file error.\n\nError: {error}")
        return
    await update.message.reply_document(
        document=text_to_file(report, "statistics_report.txt"),
        caption="Statistics report",
    )


# ============================================================
# Polynomial roots, primes, polynomial plot
# ============================================================


def parse_polynomial_coefficients(args: Sequence[str]) -> List[float]:
    if not args:
        raise ValueError("Please provide polynomial coefficients.")

    text = " ".join(args).replace(",", " ")
    parts = [part.strip() for part in text.split() if part.strip()]
    if len(parts) < 2:
        raise ValueError("A polynomial needs at least 2 coefficients.")

    coefficients = []
    for part in parts:
        try:
            coefficients.append(float(part))
        except Exception:
            raise ValueError(f"Invalid coefficient: {part}")

    while coefficients and abs(coefficients[0]) < 1e-12:
        coefficients.pop(0)

    if len(coefficients) < 2:
        raise ValueError("Leading coefficient cannot be zero.")

    degree = len(coefficients) - 1
    if degree > MAX_POLYNOMIAL_DEGREE:
        raise ValueError(f"Maximum polynomial degree is {MAX_POLYNOMIAL_DEGREE}.")

    return coefficients


def polynomial_to_text(coefficients: Sequence[float]) -> str:
    degree = len(coefficients) - 1
    terms = []

    for index, coefficient in enumerate(coefficients):
        power = degree - index
        if abs(coefficient) < 1e-12:
            continue

        abs_coefficient = abs(coefficient)
        if power == 0:
            term = format_real_number(abs_coefficient)
        elif power == 1:
            term = "x" if abs(abs_coefficient - 1) < 1e-12 else f"{format_real_number(abs_coefficient)}x"
        else:
            term = f"x^{power}" if abs(abs_coefficient - 1) < 1e-12 else f"{format_real_number(abs_coefficient)}x^{power}"

        if not terms:
            terms.append(("-" if coefficient < 0 else "") + term)
        else:
            terms.append(("- " if coefficient < 0 else "+ ") + term)

    return " ".join(terms) if terms else "0"


def evaluate_polynomial_real(coefficients: Sequence[float], x: float) -> float:
    result = 0.0
    for coefficient in coefficients:
        result = result * x + coefficient
    return result


def evaluate_polynomial_complex(coefficients: Sequence[complex], x: complex) -> complex:
    result = 0j
    for coefficient in coefficients:
        result = result * x + coefficient
    return result


def solve_polynomial_roots(coefficients: Sequence[float]) -> List[complex]:
    degree = len(coefficients) - 1
    if degree < 1:
        raise ValueError("This is not a polynomial equation.")

    if degree == 1:
        a, b = coefficients
        return [complex(-b / a)]

    if degree == 2:
        a, b, c = coefficients
        discriminant = complex(b * b - 4 * a * c)
        sqrt_discriminant = cmath.sqrt(discriminant)
        roots = [(-b + sqrt_discriminant) / (2 * a), (-b - sqrt_discriminant) / (2 * a)]
        return sorted(roots, key=lambda z: (z.real, z.imag))

    leading = coefficients[0]
    normalized = [complex(coefficient / leading) for coefficient in coefficients]
    radius = 1 + max(abs(coefficient) for coefficient in normalized[1:])
    roots = [radius * cmath.exp(2j * cmath.pi * index / degree) for index in range(degree)]

    for _ in range(2000):
        new_roots = []
        for i, root in enumerate(roots):
            denominator = 1 + 0j
            for j, other_root in enumerate(roots):
                if i == j:
                    continue
                difference = root - other_root
                if abs(difference) < 1e-14:
                    difference = complex(1e-14, 1e-14)
                denominator *= difference
            new_roots.append(root - evaluate_polynomial_complex(normalized, root) / denominator)
        max_change = max(abs(new_roots[i] - roots[i]) for i in range(degree))
        roots = new_roots
        if max_change < 1e-12:
            break

    return sorted(roots, key=lambda z: (z.real, z.imag))


def build_polynomial_roots_report(coefficients: Sequence[float], roots: Sequence[complex]) -> str:
    degree = len(coefficients) - 1
    lines = [
        "Polynomial roots",
        "",
        "Polynomial:",
        f"{polynomial_to_text(coefficients)} = 0",
        "",
        f"Degree: {degree}",
        "",
        "Roots:",
    ]
    for index, root in enumerate(roots, start=1):
        lines.append(f"x{index} = {format_complex_number(root)}")
    if degree >= 3:
        lines.extend(["", "Note: roots for degree 3 and higher are numerical approximations."])
    return "\n".join(lines)


async def polyroots_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        coefficients = parse_polynomial_coefficients(context.args)
        roots = solve_polynomial_roots(coefficients)
        report = build_polynomial_roots_report(coefficients, roots)
    except Exception as error:
        await update.message.reply_text(
            "Polynomial roots error.\n\n"
            f"Error: {error}\n\n"
            "Usage:\n/polyroots 1 -5 6\n/polyroots 1 0 -4\n/polyroots 1 0 0 -1"
        )
        return
    for chunk in split_long_text(report):
        await update.message.reply_text(chunk)


def parse_prime_limit(args: Sequence[str], allow_equal: bool = False) -> int:
    if not args:
        raise ValueError("Please provide a limit.")
    text = "".join(args).replace(",", "").replace("_", "").strip()
    if not text.isdigit():
        raise ValueError("Limit must be a positive integer.")
    limit = int(text)
    if limit < 2:
        raise ValueError("Limit must be at least 2.")
    if limit > MAX_PRIME_LIMIT:
        raise ValueError(f"Limit is too large. Maximum allowed is {MAX_PRIME_LIMIT}.")
    return limit


def primes_less_than(limit: int) -> List[int]:
    if limit <= 2:
        return []
    sieve = bytearray(b"\x01") * limit
    sieve[0:2] = b"\x00\x00"
    max_check = int(limit ** 0.5) + 1
    for number in range(2, max_check):
        if sieve[number]:
            start = number * number
            count = ((limit - 1 - start) // number) + 1
            sieve[start:limit:number] = b"\x00" * count
    return [number for number in range(limit) if sieve[number]]


def build_primes_report(limit: int, primes: Sequence[int]) -> str:
    return f"Prime numbers less than {limit}\n\nCount: {len(primes)}\n\n" + (
        ", ".join(str(prime) for prime in primes) if primes else "No prime numbers found."
    )


async def primes_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        limit = parse_prime_limit(context.args)
        primes = primes_less_than(limit)
        report = build_primes_report(limit, primes)
    except Exception as error:
        await update.message.reply_text(f"Prime numbers error.\n\nError: {error}\n\nUsage:\n/primes 100")
        return
    if len(report) <= 3500:
        await update.message.reply_text(report)
    else:
        await update.message.reply_document(
            document=text_to_file(report, f"primes_less_than_{limit}.txt"),
            caption=f"Prime numbers less than {limit}",
        )


async def primesfile_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        limit = parse_prime_limit(context.args)
        primes = primes_less_than(limit)
        report = build_primes_report(limit, primes)
    except Exception as error:
        await update.message.reply_text(f"Prime file error.\n\nError: {error}\n\nUsage:\n/primesfile 10000")
        return
    await update.message.reply_document(
        document=text_to_file(report, f"primes_less_than_{limit}.txt"),
        caption=f"Prime numbers less than {limit}",
    )


# ============================================================
# Plotting engine
# ============================================================


def load_plot_font(size: int = 22):
    for font_path in [
        "arial.ttf",
        "DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]:
        try:
            return ImageFont.truetype(font_path, size)
        except Exception:
            pass
    return ImageFont.load_default()


def nice_number(value: float) -> str:
    if not math.isfinite(value):
        return str(value)
    value = clean_number(value)
    if abs(value - round(value)) < 1e-9:
        return str(int(round(value)))
    return f"{value:.4g}"


def robust_range(values: List[float], include_zero: bool = True) -> Tuple[float, float]:
    finite = sorted(v for v in values if math.isfinite(v) and abs(v) < 1e100)
    if not finite:
        return -1.0, 1.0
    low_index = max(0, int(len(finite) * 0.02))
    high_index = min(len(finite) - 1, int(len(finite) * 0.98))
    low = finite[low_index]
    high = finite[high_index]
    if include_zero:
        low = min(low, 0.0)
        high = max(high, 0.0)
    if abs(high - low) < 1e-12:
        low -= 1.0
        high += 1.0
    padding = (high - low) * 0.10
    return low - padding, high + padding


def create_xy_plot_image(
    series: List[Dict[str, Any]],
    title: str,
    x_range: Optional[Tuple[float, float]] = None,
    y_range: Optional[Tuple[float, float]] = None,
    xlabel: str = "x",
    ylabel: str = "y",
    shaded_area: Optional[Dict[str, Any]] = None,
    points_to_mark: Optional[List[Tuple[float, float, str]]] = None,
    filename: str = "math_plot.png",
) -> BytesIO:
    width = DEFAULT_PLOT_WIDTH
    height = DEFAULT_PLOT_HEIGHT
    margin_left = 95
    margin_right = 45
    margin_top = 80
    margin_bottom = 95
    plot_left = margin_left
    plot_right = width - margin_right
    plot_top = margin_top
    plot_bottom = height - margin_bottom
    plot_width = plot_right - plot_left
    plot_height = plot_bottom - plot_top

    all_x = []
    all_y = []
    for item in series:
        for point in item.get("points", []):
            if point is None:
                continue
            x, y = point
            if math.isfinite(x) and math.isfinite(y):
                all_x.append(x)
                all_y.append(y)

    if shaded_area:
        for point in shaded_area.get("points", []):
            if point is None:
                continue
            x, y = point
            if math.isfinite(x) and math.isfinite(y):
                all_x.append(x)
                all_y.append(y)
                all_y.append(0.0)

    if points_to_mark:
        for x, y, _ in points_to_mark:
            all_x.append(x)
            all_y.append(y)

    if x_range is None:
        xmin, xmax = robust_range(all_x, include_zero=False)
    else:
        xmin, xmax = x_range
    if y_range is None:
        ymin, ymax = robust_range(all_y, include_zero=True)
    else:
        ymin, ymax = y_range

    if xmin >= xmax or ymin >= ymax:
        raise ValueError("Invalid plot range.")

    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    title_font = load_plot_font(30)
    label_font = load_plot_font(20)
    small_font = load_plot_font(16)

    draw.text((margin_left, 26), title[:90], fill="black", font=title_font)

    def map_x(x: float) -> int:
        return int(plot_left + (x - xmin) / (xmax - xmin) * plot_width)

    def map_y(y: float) -> int:
        return int(plot_bottom - (y - ymin) / (ymax - ymin) * plot_height)

    draw.rectangle((plot_left, plot_top, plot_right, plot_bottom), outline="#222222", width=2, fill="#fbfbfb")

    grid_lines = 10
    for i in range(grid_lines + 1):
        gx = plot_left + i * plot_width / grid_lines
        gy = plot_top + i * plot_height / grid_lines
        draw.line((gx, plot_top, gx, plot_bottom), fill="#dddddd", width=1)
        draw.line((plot_left, gy, plot_right, gy), fill="#dddddd", width=1)

    if xmin <= 0 <= xmax:
        x0 = map_x(0)
        draw.line((x0, plot_top, x0, plot_bottom), fill="#333333", width=3)
    if ymin <= 0 <= ymax:
        y0 = map_y(0)
        draw.line((plot_left, y0, plot_right, y0), fill="#333333", width=3)

    for i in range(grid_lines + 1):
        x_value = xmin + i * (xmax - xmin) / grid_lines
        x_pixel = plot_left + i * plot_width / grid_lines
        draw.text((x_pixel - 22, plot_bottom + 16), nice_number(x_value), fill="#333333", font=small_font)

        y_value = ymax - i * (ymax - ymin) / grid_lines
        y_pixel = plot_top + i * plot_height / grid_lines
        draw.text((12, y_pixel - 9), nice_number(y_value), fill="#333333", font=small_font)

    draw.text((plot_right - 20, plot_bottom + 46), xlabel, fill="black", font=label_font)
    draw.text((22, plot_top - 35), ylabel, fill="black", font=label_font)

    if shaded_area:
        shade_points = []
        curve_pixels = []
        base_pixels = []
        for point in shaded_area.get("points", []):
            if point is None:
                continue
            x, y = point
            if not (xmin <= x <= xmax and math.isfinite(y)):
                continue
            clipped_y = max(min(y, ymax), ymin)
            curve_pixels.append((map_x(x), map_y(clipped_y)))
            base_pixels.append((map_x(x), map_y(0.0)))
        if len(curve_pixels) >= 2:
            shade_points = curve_pixels + list(reversed(base_pixels))
            draw.polygon(shade_points, fill="#cfe3ff")

    default_colors = ["#1f77b4", "#d62728", "#2ca02c", "#9467bd", "#ff7f0e"]
    for idx, item in enumerate(series):
        color = item.get("color", default_colors[idx % len(default_colors)])
        width_line = item.get("width", 4)
        pixel_points = []
        for point in item.get("points", []):
            if point is None:
                pixel_points.append(None)
                continue
            x, y = point
            if not (math.isfinite(x) and math.isfinite(y)) or y < ymin or y > ymax or x < xmin or x > xmax:
                pixel_points.append(None)
                continue
            pixel_points.append((map_x(x), map_y(y)))

        current_segment = []
        for point in pixel_points:
            if point is None:
                if len(current_segment) >= 2:
                    draw.line(current_segment, fill=color, width=width_line)
                current_segment = []
            else:
                current_segment.append(point)
        if len(current_segment) >= 2:
            draw.line(current_segment, fill=color, width=width_line)

    if points_to_mark:
        for x, y, label in points_to_mark:
            if not (xmin <= x <= xmax and ymin <= y <= ymax):
                continue
            px = map_x(x)
            py = map_y(y)
            draw.ellipse((px - 7, py - 7, px + 7, py + 7), fill="#d62728")
            if label:
                draw.text((px + 10, py - 24), label, fill="#d62728", font=small_font)

    draw.text(
        (margin_left, height - 42),
        f"x: [{nice_number(xmin)}, {nice_number(xmax)}] | y: [{nice_number(ymin)}, {nice_number(ymax)}] | {now_note()}",
        fill="#555555",
        font=small_font,
    )

    output = BytesIO()
    image.save(output, format="PNG")
    output.seek(0)
    output.name = filename
    return output


def sample_function_points(expr: str, xmin: float, xmax: float, variable_name: str = "x", samples: int = MAX_PLOT_SAMPLES) -> List[Optional[Tuple[float, float]]]:
    points: List[Optional[Tuple[float, float]]] = []
    previous_y: Optional[float] = None
    for i in range(samples + 1):
        x = xmin + (xmax - xmin) * i / samples
        try:
            y = evaluate_function(expr, variable_name, x)
            if not math.isfinite(y) or abs(y) > 1e100:
                points.append(None)
                previous_y = None
                continue
            if previous_y is not None and abs(y - previous_y) > 1e6 * max(1, abs(previous_y)):
                points.append(None)
            points.append((x, y))
            previous_y = y
        except Exception:
            points.append(None)
            previous_y = None
    return points


def parse_keyword_range(args: Sequence[str], default: Tuple[float, float]) -> Tuple[str, float, float]:
    if not args:
        raise ValueError("Please provide an expression.")
    lowered = [arg.lower() for arg in args]
    if "range" in lowered:
        idx = lowered.index("range")
        expr = " ".join(args[:idx]).strip()
        range_args = args[idx + 1:]
        if len(range_args) != 2:
            raise ValueError("Range must be: range xmin xmax")
        xmin = float(range_args[0])
        xmax = float(range_args[1])
    else:
        expr = " ".join(args).strip()
        xmin, xmax = default
    if not expr:
        raise ValueError("Expression is empty.")
    if xmin >= xmax:
        raise ValueError("xmin must be smaller than xmax.")
    if xmax - xmin > 1_000_000:
        raise ValueError("Range is too large.")
    return expr, xmin, xmax


async def send_plot(update: Update, image: BytesIO, caption: str) -> None:
    if update.message:
        await update.message.reply_photo(photo=InputFile(image, filename=image.name), caption=caption[:1024])


# ============================================================
# Polynomial plot
# ============================================================


def parse_polyplot_args(args: Sequence[str]) -> Tuple[List[float], float, float]:
    lowered = [arg.lower() for arg in args]
    if "range" in lowered:
        idx = lowered.index("range")
        coefficients = parse_polynomial_coefficients(args[:idx])
        range_args = args[idx + 1:]
        if len(range_args) != 2:
            raise ValueError("Range must be: range xmin xmax")
        xmin = float(range_args[0])
        xmax = float(range_args[1])
    else:
        coefficients = parse_polynomial_coefficients(args)
        degree = len(coefficients) - 1
        xmin, xmax = (-10.0, 10.0) if degree <= 2 else (-5.0, 5.0)
    if xmin >= xmax:
        raise ValueError("xmin must be smaller than xmax.")
    return coefficients, xmin, xmax


def create_polynomial_plot_image(coefficients: Sequence[float], xmin: float, xmax: float) -> BytesIO:
    points = [(x, evaluate_polynomial_real(coefficients, x)) for x, _ in sample_even_x(xmin, xmax, MAX_PLOT_SAMPLES)]
    marks = []
    if len(coefficients) - 1 <= 10:
        try:
            roots = solve_polynomial_roots(coefficients)
            for root in roots:
                if abs(root.imag) < 1e-7 and xmin <= root.real <= xmax:
                    marks.append((root.real, 0.0, f"x={nice_number(root.real)}"))
        except Exception:
            pass
    title = f"Polynomial: {polynomial_to_text(coefficients)}"
    return create_xy_plot_image(
        [{"points": points, "color": "#1f77b4", "width": 4}],
        title=title,
        x_range=(xmin, xmax),
        xlabel="x",
        ylabel="f(x)",
        points_to_mark=marks,
        filename="polynomial_plot.png",
    )


def sample_even_x(xmin: float, xmax: float, samples: int) -> Iterable[Tuple[float, int]]:
    for i in range(samples + 1):
        yield xmin + (xmax - xmin) * i / samples, i


async def polyplot_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        coefficients, xmin, xmax = parse_polyplot_args(context.args)
        image = create_polynomial_plot_image(coefficients, xmin, xmax)
        caption = f"Plot of {polynomial_to_text(coefficients)}"
    except Exception as error:
        await update.message.reply_text(
            "Polynomial plot error.\n\n"
            f"Error: {error}\n\n"
            "Usage:\n/polyplot 1 -5 6\n/polyplot 1 -5 6 range -2 8"
        )
        return
    await send_plot(update, image, caption)


# ============================================================
# 1. General function plot
# ============================================================


async def plot_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, xmin, xmax = parse_keyword_range(context.args, default=(-10.0, 10.0))
        points = sample_function_points(expr, xmin, xmax, "x")
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 4}],
            title=f"f(x) = {expr}",
            x_range=(xmin, xmax),
            xlabel="x",
            ylabel="f(x)",
            filename="function_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(
            f"Function plot error.\n\nError: {error}\n\n"
            "Usage:\n/plot sin(x) range -6.28 6.28\n/plot exp(-x^2) range -3 3"
        )
        return
    await send_plot(update, image, f"Plot of f(x) = {expr}")


# ============================================================
# 2. Derivative and tangent line plot
# ============================================================


def parse_at_command(args: Sequence[str], keyword: str = "at") -> Tuple[str, float]:
    lowered = [arg.lower() for arg in args]
    if keyword not in lowered:
        raise ValueError(f"Use: {keyword} x0")
    idx = lowered.index(keyword)
    expr = " ".join(args[:idx]).strip()
    rest = args[idx + 1:]
    if len(rest) != 1:
        raise ValueError(f"Use exactly one number after {keyword}.")
    if not expr:
        raise ValueError("Expression is empty.")
    return expr, float(rest[0])


def numerical_derivative(expr: str, x: float) -> float:
    h = 1e-5 * max(1.0, abs(x))
    return (evaluate_function(expr, "x", x + h) - evaluate_function(expr, "x", x - h)) / (2 * h)


def tangent_line_value(slope: float, x0: float, y0: float, x: float) -> float:
    return slope * (x - x0) + y0


async def derivative_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, x0 = parse_at_command(context.args, "at")
        y0 = evaluate_function(expr, "x", x0)
        slope = numerical_derivative(expr, x0)
        b = y0 - slope * x0
        text = (
            "Numerical derivative\n\n"
            f"f(x) = {expr}\n"
            f"x = {format_real_number(x0)}\n"
            f"f(x) = {format_real_number(y0)}\n"
            f"f'(x) ≈ {format_real_number(slope)}\n"
            f"Tangent line: y = {format_real_number(slope)}x {'+' if b >= 0 else '-'} {format_real_number(abs(b))}"
        )
    except Exception as error:
        await update.message.reply_text(
            f"Derivative error.\n\nError: {error}\n\nUsage:\n/derivative x^3 - 2*x at 2"
        )
        return
    await update.message.reply_text(text)


async def tangent_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, x0 = parse_at_command(context.args, "at")
        y0 = evaluate_function(expr, "x", x0)
        slope = numerical_derivative(expr, x0)
        xmin = x0 - 5
        xmax = x0 + 5
        points = sample_function_points(expr, xmin, xmax, "x")
        tangent_points = [(x, tangent_line_value(slope, x0, y0, x)) for x, _ in sample_even_x(xmin, xmax, 100)]
        image = create_xy_plot_image(
            [
                {"points": points, "color": "#1f77b4", "width": 4},
                {"points": tangent_points, "color": "#d62728", "width": 3},
            ],
            title=f"Tangent line for f(x) = {expr}",
            x_range=(xmin, xmax),
            xlabel="x",
            ylabel="y",
            points_to_mark=[(x0, y0, f"({nice_number(x0)}, {nice_number(y0)})")],
            filename="tangent_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(f"Tangent plot error.\n\nError: {error}\n\nUsage:\n/tangent x^3 - 2*x at 2")
        return
    await send_plot(update, image, f"Tangent slope ≈ {format_real_number(slope)}")


# ============================================================
# 3. Integral and area plot
# ============================================================


def parse_from_to(args: Sequence[str]) -> Tuple[str, float, float]:
    lowered = [arg.lower() for arg in args]
    if "from" not in lowered or "to" not in lowered:
        raise ValueError("Use: from a to b")
    from_idx = lowered.index("from")
    to_idx = lowered.index("to")
    if to_idx <= from_idx:
        raise ValueError("Use: from a to b")
    expr = " ".join(args[:from_idx]).strip()
    if not expr:
        raise ValueError("Expression is empty.")
    if to_idx != from_idx + 2:
        raise ValueError("Use exactly one number after from.")
    if len(args) != to_idx + 2:
        raise ValueError("Use exactly one number after to.")
    a = float(args[from_idx + 1])
    b = float(args[to_idx + 1])
    if a == b:
        raise ValueError("Integration bounds cannot be equal.")
    return expr, a, b


def numerical_integral(expr: str, a: float, b: float, n: int = 1000) -> float:
    if n % 2 == 1:
        n += 1
    h = (b - a) / n
    total = evaluate_function(expr, "x", a) + evaluate_function(expr, "x", b)
    for i in range(1, n):
        x = a + i * h
        total += (4 if i % 2 else 2) * evaluate_function(expr, "x", x)
    return total * h / 3


async def integral_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, a, b = parse_from_to(context.args)
        value = numerical_integral(expr, a, b)
        text = (
            "Numerical integral\n\n"
            f"f(x) = {expr}\n"
            f"Interval: [{format_real_number(a)}, {format_real_number(b)}]\n"
            f"Integral ≈ {format_real_number(value, digits=14)}"
        )
    except Exception as error:
        await update.message.reply_text(f"Integral error.\n\nError: {error}\n\nUsage:\n/integral x^2 from 0 to 3")
        return
    await update.message.reply_text(text)


async def areaplot_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, a, b = parse_from_to(context.args)
        left = min(a, b)
        right = max(a, b)
        padding = (right - left) * 0.25 or 1
        xmin = left - padding
        xmax = right + padding
        points = sample_function_points(expr, xmin, xmax, "x")
        area_points = sample_function_points(expr, left, right, "x", samples=250)
        value = numerical_integral(expr, a, b)
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 4}],
            title=f"Area under f(x) = {expr}",
            x_range=(xmin, xmax),
            xlabel="x",
            ylabel="f(x)",
            shaded_area={"points": area_points},
            filename="area_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(f"Area plot error.\n\nError: {error}\n\nUsage:\n/areaplot sin(x) from 0 to 3.14")
        return
    await send_plot(update, image, f"Area / integral ≈ {format_real_number(value, digits=14)}")


# ============================================================
# 4. Newton method plot
# ============================================================


def parse_start_command(args: Sequence[str]) -> Tuple[str, float]:
    lowered = [arg.lower() for arg in args]
    if "start" not in lowered:
        raise ValueError("Use: start x0")
    idx = lowered.index("start")
    expr = " ".join(args[:idx]).strip()
    rest = args[idx + 1:]
    if not expr:
        raise ValueError("Expression is empty.")
    if len(rest) != 1:
        raise ValueError("Use exactly one start value.")
    return expr, float(rest[0])


def newton_iterations(expr: str, start: float, max_iter: int = 20) -> List[Tuple[int, float, float]]:
    x = start
    result = []
    for i in range(max_iter):
        y = evaluate_function(expr, "x", x)
        result.append((i, x, y))
        if abs(y) < 1e-10:
            break
        d = numerical_derivative(expr, x)
        if abs(d) < 1e-12:
            raise ValueError("Derivative became too close to zero.")
        x = x - y / d
        if not math.isfinite(x) or abs(x) > 1e12:
            raise ValueError("Newton method diverged.")
    return result


async def newton_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, start = parse_start_command(context.args)
        iterations = newton_iterations(expr, start)
        root = iterations[-1][1]
        xmin = min(x for _, x, _ in iterations) - 2
        xmax = max(x for _, x, _ in iterations) + 2
        if xmin == xmax:
            xmin, xmax = root - 5, root + 5
        points = sample_function_points(expr, xmin, xmax, "x")
        marks = [(x, y, f"x{i}") for i, x, y in iterations[:8]]
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 4}],
            title=f"Newton method: f(x) = {expr}",
            x_range=(xmin, xmax),
            xlabel="x",
            ylabel="f(x)",
            points_to_mark=marks,
            filename="newton_plot.png",
        )
        lines = ["Newton method", "", f"f(x) = {expr}", f"Approx root: x ≈ {format_real_number(root, digits=14)}", "", "Iterations:"]
        for i, x, y in iterations:
            lines.append(f"x{i} = {format_real_number(x, digits=12)}, f(x{i}) = {format_real_number(y, digits=12)}")
    except Exception as error:
        await update.message.reply_text(f"Newton method error.\n\nError: {error}\n\nUsage:\n/newton x^3 - x - 2 start 1")
        return
    await update.message.reply_text("\n".join(lines))
    await send_plot(update, image, f"Newton root ≈ {format_real_number(root, digits=14)}")


# ============================================================
# 5. Prime counting and prime gap plots
# ============================================================


async def primecount_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        limit = parse_prime_limit(context.args)
        primes = primes_less_than(limit + 1)
        prime_set = set(primes)
        step = max(1, limit // 500)
        points = []
        count = 0
        for n in range(2, limit + 1):
            if n in prime_set:
                count += 1
            if n % step == 0 or n == limit:
                points.append((float(n), float(count)))
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 4}],
            title=f"Prime counting function π(n), n ≤ {limit}",
            x_range=(2, limit),
            xlabel="n",
            ylabel="π(n)",
            filename="primecount_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(f"Prime count plot error.\n\nError: {error}\n\nUsage:\n/primecount 1000")
        return
    await send_plot(update, image, f"There are {len(primes)} primes ≤ {limit}.")


async def primegap_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        limit = parse_prime_limit(context.args)
        primes = primes_less_than(limit + 1)
        if len(primes) < 2:
            raise ValueError("Need at least two primes.")
        gaps = [(float(primes[i]), float(primes[i] - primes[i - 1])) for i in range(1, len(primes))]
        image = create_xy_plot_image(
            [{"points": gaps, "color": "#1f77b4", "width": 3}],
            title=f"Prime gaps up to {limit}",
            x_range=(2, limit),
            xlabel="prime p",
            ylabel="gap from previous prime",
            filename="primegap_plot.png",
        )
        max_gap = max(int(gap) for _, gap in gaps)
    except Exception as error:
        await update.message.reply_text(f"Prime gap plot error.\n\nError: {error}\n\nUsage:\n/primegap 500")
        return
    await send_plot(update, image, f"Prime gaps up to {limit}. Max gap: {max_gap}")


# ============================================================
# 6. Collatz plot
# ============================================================


async def collatzplot_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        n = parse_positive_int(context.args, "Collatz input", max_value=10_000_000)
        seq = collatz_sequence(n)
        if len(seq) > 5000:
            raise ValueError("Sequence is too long to plot.")
        points = [(float(i), float(value)) for i, value in enumerate(seq)]
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 3}],
            title=f"Collatz sequence for {n}",
            x_range=(0, len(seq) - 1),
            xlabel="step",
            ylabel="value",
            filename="collatz_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(f"Collatz plot error.\n\nError: {error}\n\nUsage:\n/collatzplot 27")
        return
    await send_plot(update, image, f"Collatz plot for {n}. Steps: {len(seq) - 1}, max: {max(seq)}")


# ============================================================
# 7. Fibonacci spiral
# ============================================================


def create_fib_spiral_image(n: int) -> BytesIO:
    if n < 2:
        raise ValueError("Use at least 2 squares.")
    if n > 16:
        raise ValueError("Maximum Fibonacci spiral size is 16.")
    fibs = [1, 1]
    for _ in range(2, n):
        fibs.append(fibs[-1] + fibs[-2])

    # Place squares in a spiral using directions right, up, left, down.
    squares = []
    x, y = 0, 0
    squares.append((x, y, fibs[0], 0))
    x += fibs[0]
    squares.append((x, y, fibs[1], 1))
    directions = [(0, -1), (-1, 0), (0, 1), (1, 0)]
    for i in range(2, n):
        size = fibs[i]
        direction_index = (i - 2) % 4
        dx, dy = directions[direction_index]
        if direction_index == 0:  # up
            x = squares[-1][0]
            y = squares[-1][1] - size
        elif direction_index == 1:  # left
            x = squares[-1][0] - size
            y = squares[-1][1]
        elif direction_index == 2:  # down
            x = squares[-1][0]
            y = squares[-1][1] + squares[-1][2]
        else:  # right
            x = squares[-1][0] + squares[-1][2]
            y = squares[-1][1]
        squares.append((x, y, size, direction_index))

    min_x = min(s[0] for s in squares)
    min_y = min(s[1] for s in squares)
    max_x = max(s[0] + s[2] for s in squares)
    max_y = max(s[1] + s[2] for s in squares)
    width = 1100
    height = 850
    margin = 70
    scale = min((width - 2 * margin) / (max_x - min_x), (height - 2 * margin) / (max_y - min_y))

    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    title_font = load_plot_font(32)
    small_font = load_plot_font(16)
    draw.text((margin, 25), f"Fibonacci spiral with {n} squares", fill="black", font=title_font)

    def tx(v: float) -> int:
        return int(margin + (v - min_x) * scale)

    def ty(v: float) -> int:
        return int(margin + 45 + (v - min_y) * scale)

    for i, (sx, sy, size, direction_index) in enumerate(squares):
        x1, y1, x2, y2 = tx(sx), ty(sy), tx(sx + size), ty(sy + size)
        draw.rectangle((x1, y1, x2, y2), outline="#333333", width=2)
        draw.text((x1 + 5, y1 + 5), str(size), fill="#555555", font=small_font)

        # Approximate spiral quarter arcs.
        if i == 0:
            continue
        if direction_index == 0:
            bbox = (x1, y1, x2 * 2 - x1, y2 * 2 - y1)
            start, end = 180, 270
        elif direction_index == 1:
            bbox = (x1, y1, x2, y2)
            start, end = 270, 360
        elif direction_index == 2:
            bbox = (x1, y1, x2, y2)
            start, end = 0, 90
        else:
            bbox = (x1, y1, x2, y2)
            start, end = 90, 180
        try:
            draw.arc(bbox, start=start, end=end, fill="#d62728", width=4)
        except Exception:
            pass

    output = BytesIO()
    image.save(output, format="PNG")
    output.seek(0)
    output.name = "fibonacci_spiral.png"
    return output


async def fibspiral_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        n = parse_positive_int(context.args, "Fibonacci spiral size", max_value=16)
        image = create_fib_spiral_image(n)
    except Exception as error:
        await update.message.reply_text(f"Fibonacci spiral error.\n\nError: {error}\n\nUsage:\n/fibspiral 10")
        return
    await send_plot(update, image, f"Fibonacci spiral with {n} squares")


# ============================================================
# 8. Polar plot
# ============================================================


async def polarplot_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        expr, theta_min, theta_max = parse_keyword_range(context.args, default=(0.0, math.tau))
        points = []
        for theta, _ in sample_even_x(theta_min, theta_max, MAX_PLOT_SAMPLES):
            try:
                r = evaluate_function(expr, "theta", theta)
                x = r * math.cos(theta)
                y = r * math.sin(theta)
                if math.isfinite(x) and math.isfinite(y):
                    points.append((x, y))
                else:
                    points.append(None)
            except Exception:
                points.append(None)
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 4}],
            title=f"Polar plot: r = {expr}",
            xlabel="x",
            ylabel="y",
            filename="polar_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(
            f"Polar plot error.\n\nError: {error}\n\nUsage:\n/polarplot 1 + sin(theta) range 0 6.28"
        )
        return
    await send_plot(update, image, f"Polar plot of r = {expr}")


# ============================================================
# 9. Parametric plot
# ============================================================


def parse_paramplot_args(args: Sequence[str]) -> Tuple[str, str, float, float]:
    if not args:
        raise ValueError("Please provide x(t) and y(t).")
    text = " ".join(args)
    lowered = [arg.lower() for arg in args]
    tmin, tmax = 0.0, math.tau
    before = text
    if "range" in lowered:
        idx = lowered.index("range")
        before = " ".join(args[:idx])
        range_args = args[idx + 1:]
        if len(range_args) != 2:
            raise ValueError("Range must be: range tmin tmax")
        tmin = float(range_args[0])
        tmax = float(range_args[1])

    if ";" in before:
        x_expr, y_expr = [part.strip() for part in before.split(";", 1)]
    elif "," in before:
        x_expr, y_expr = [part.strip() for part in before.split(",", 1)]
    else:
        parts = before.split()
        if len(parts) < 2:
            raise ValueError("Use semicolon between expressions, e.g. cos(t); sin(t)")
        x_expr = parts[0]
        y_expr = " ".join(parts[1:])

    if not x_expr or not y_expr:
        raise ValueError("Both x(t) and y(t) are required.")
    if tmin >= tmax:
        raise ValueError("tmin must be smaller than tmax.")
    return x_expr, y_expr, tmin, tmax


async def paramplot_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not update.message:
        return
    try:
        x_expr, y_expr, tmin, tmax = parse_paramplot_args(context.args)
        points = []
        for t, _ in sample_even_x(tmin, tmax, MAX_PLOT_SAMPLES):
            try:
                x = evaluate_function(x_expr, "t", t)
                y = evaluate_function(y_expr, "t", t)
                if math.isfinite(x) and math.isfinite(y):
                    points.append((x, y))
                else:
                    points.append(None)
            except Exception:
                points.append(None)
        image = create_xy_plot_image(
            [{"points": points, "color": "#1f77b4", "width": 4}],
            title=f"Parametric plot: x={x_expr}, y={y_expr}",
            xlabel="x(t)",
            ylabel="y(t)",
            filename="parametric_plot.png",
        )
    except Exception as error:
        await update.message.reply_text(
            f"Parametric plot error.\n\nError: {error}\n\n"
            "Usage:\n/paramplot cos(t); sin(t) range 0 6.28\n/paramplot sin(3*t); sin(4*t) range 0 6.28"
        )
        return
    await send_plot(update, image, f"Parametric plot: x={x_expr}, y={y_expr}")


# ============================================================
# Help
# ============================================================


def math_help_text() -> str:
    return (
        "Math commands\n\n"
        "Calculator and sequences:\n"
        "/calc sin(pi / 2) + sqrt(16)\n"
        "/collatz 27\n"
        "/fib 100\n"
        "/fiblist 20\n"
        "/stats 4, pi, 4, sin(pi/2), 7, 2\n\n"
        "Polynomials and primes:\n"
        "/polyroots 1 -5 6\n"
        "/polyplot 1 -5 6 range -2 8\n"
        "/primes 100\n"
        "/primesfile 10000\n\n"
        "Plots and analysis:\n"
        "/plot sin(x) range -6.28 6.28\n"
        "/derivative x^3 - 2*x at 2\n"
        "/tangent x^3 - 2*x at 2\n"
        "/integral x^2 from 0 to 3\n"
        "/areaplot sin(x) from 0 to 3.14\n"
        "/newton x^3 - x - 2 start 1\n"
        "/primecount 1000\n"
        "/primegap 500\n"
        "/collatzplot 27\n"
        "/fibspiral 10\n"
        "/polarplot 1 + sin(theta) range 0 6.28\n"
        "/paramplot cos(t); sin(t) range 0 6.28"
    )


async def mathhelp_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if update.message:
        await update.message.reply_text(math_help_text())


# ============================================================
# Registration
# ============================================================


def register_math_handlers(app: Application) -> None:
    app.add_handler(CommandHandler("calc", calc_command))
    app.add_handler(CommandHandler("calculate", calc_command))
    app.add_handler(CommandHandler("calculator", calc_command))
    app.add_handler(CommandHandler("pi", pi_command))
    app.add_handler(CommandHandler("e", e_command))

    app.add_handler(CommandHandler("collatz", collatz_command))
    app.add_handler(CommandHandler("fib", fib_command))
    app.add_handler(CommandHandler("fibonacci", fib_command))
    app.add_handler(CommandHandler("fiblist", fiblist_command))

    app.add_handler(CommandHandler("stats", stats_command))
    app.add_handler(CommandHandler("statistics", stats_command))
    app.add_handler(CommandHandler("statsfile", statsfile_command))

    app.add_handler(CommandHandler("polyroots", polyroots_command))
    app.add_handler(CommandHandler("roots", polyroots_command))
    app.add_handler(CommandHandler("primes", primes_command))
    app.add_handler(CommandHandler("primesfile", primesfile_command))
    app.add_handler(CommandHandler("polyplot", polyplot_command))
    app.add_handler(CommandHandler("plotpoly", polyplot_command))

    app.add_handler(CommandHandler("plot", plot_command))
    app.add_handler(CommandHandler("derivative", derivative_command))
    app.add_handler(CommandHandler("tangent", tangent_command))
    app.add_handler(CommandHandler("integral", integral_command))
    app.add_handler(CommandHandler("areaplot", areaplot_command))
    app.add_handler(CommandHandler("newton", newton_command))
    app.add_handler(CommandHandler("primecount", primecount_command))
    app.add_handler(CommandHandler("primegap", primegap_command))
    app.add_handler(CommandHandler("collatzplot", collatzplot_command))
    app.add_handler(CommandHandler("fibspiral", fibspiral_command))
    app.add_handler(CommandHandler("polarplot", polarplot_command))
    app.add_handler(CommandHandler("paramplot", paramplot_command))

    app.add_handler(CommandHandler("mathhelp", mathhelp_command))
